export const locators = {
  loginUsername: '[name="username"]',
  loginPassword: '[name="password"]',
  signInButton: '[class="MuiButton-label"]',
  albumCover: '[class="MuiGridListTile-tile"]',
  playAlbumButton: '[aria-label="play"]',
  currentTime: '[class="current-time"]',
  pauseSongButton: "//span[@title='Click to pause']",
  playSongButton: "//span[@title='Click to play']",
  songTitle: "[class*='jss'] .songTitle",
  nextTrackButton: "span[title='Next track'] svg",
  previousTrackButton: "span[title='Previous track'] svg",
  volumeButton: "//span[@class='sounds-icon']//*[name()='svg']",
  volumeBar: '[class="rc-slider-track"]',
  favouritesButton: '[record="[object Object]"]',
  favouritesSectionLink: "(//a[normalize-space()='Favourites'])",
  albumName: ".MuiTypography-root.MuiTypography-body1",
  searchBar: '[id="search"]',
  recentlyPlayedSectionLink: "(//a[normalize-space()='Recently Played'])",
  tableWithSongs: "MuiCard-root",
  playButton: '[aria-label="Play"]',
  shuffleButton: '[aria-label="Shuffle"]',
  playNextButton: '[aria-label="Play Next"]',
  fourStarRating: "label[for='6f8a42a6637a13b7d9ee740660ac16a5-4']",
  starFilled:
    "label[for='6f8a42a6637a13b7d9ee740660ac16a5-4'] span[class='MuiRating-icon MuiRating-iconFilled']",
  songOnAlbum: ".MuiTableRow-root.MuiTableRow-hover",
  fourStarRatingSong: "label[for='eb9a728d0f6e3d80b91f41bc881309f1-4']",
  starFilledSong:
    "label[for='eb9a728d0f6e3d80b91f41bc881309f1-4'] span[class='MuiRating-icon MuiRating-iconFilled']",
  addToPlaylistButton: '[aria-label="Add to Playlist"]',
  playlistNameField: '[id="select-playlist-input"]',
  addPlaylistButton: "//span[normalize-space()='Add']",
  addPlaylistWindow: '[id="form-dialog-new-playlist"]',
  songsAddedToPlaylistAlert: "div[role='alert']",
  shareButton: "Share",
  shareDescriptionField: '[id="description"]',
  optionsOnShareWindow:
    '[class="MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary"]',
  urlCopiedSuccessMessage: '[class="MuiSnackbarContent-message"]',
  downloadButton: 'button:has-text("download")',
  favouriteButtonOnSong:
    ".MuiButtonBase-root.MuiIconButton-root.MuiIconButton-sizeSmall",
  songsSectionLink: "(//a[normalize-space()='Songs'])",
  songNameOnAlbum: ".MuiTypography-root.MuiTypography-body2",
  favouritesFilter: '[data-key="starred"]',
  searchSongsField: '[id="title"]',
  tableLayout: '[aria-label="Table"]',
  addFilterButton: "Add filter",
  yearOption: "Year",
  yearField: '[id="year"]',
  orderOfSongsButton: '[class="group loop-btn"]',
  closePanelButton: '[title="Destroy"]',
  panel: '[class="panel-content"]',
  contextMenuOnAlbumButton: '[aria-controls="context-menu"]',
  infoMenuItem: '[value="info"]',
  infoDialog: '[aria-labelledby="info-dialog-album"]',
  playMenuItem: '[value="play"]',
  shuffleMenuItem: '[value="shuffle"]',
  addToPlaylistMenuItem: '[value="addToPlaylist"]',
  shareMenuItem: '[value="share"]',
  downloadMenuItem: '[value="download"]',
  artistNameOnAlbum: '[href="#/artist/a6c193b21fd1fa6639a278e4f3e64b05/show"]',
  artistNameOnArtistPage: ".MuiTypography-root.MuiTypography-h5",
  listItemsPerPageButton: '[aria-haspopup="listbox"]',
  option: '[role="option"]',
  artistsSectionLink: "Artists",
  tableWithArtists: ".MuiTable-root",
  artistFromTable: ".MuiTableRow-root.MuiTableRow-hover",
  artistContextMenu: '[aria-controls="context-menu"]',
  artistName:
    ".MuiTableCell-root.MuiTableCell-body.column-name.MuiTableCell-sizeSmall",
  threeStarRatingArtist: "label[for='8c3950ec37c25e2c780193ea5e9e8a12-3']",
  threeStarFilled:
    "label[for='8c3950ec37c25e2c780193ea5e9e8a12-3'] span[class='MuiRating-icon MuiRating-iconFilled']",
  artistNameInFavourites:
    ".MuiTableCell-root.MuiTableCell-body.column-name.MuiTableCell-sizeSmall",
  tableSongs: ".MuiTable-root",
  songFromTable: ".MuiTableRow-root.MuiTableRow-hover",
  shuffleAllButton: '[aria-label="Shuffle All"]',
  albumNameFromSongs:
    ".MuiTableCell-root.MuiTableCell-body.column-album.MuiTableCell-sizeSmall",
  header: ".MuiPaper-root.MuiCard-root.MuiPaper-elevation1.MuiPaper-rounded",
  artistNameFromSongs:
    ".MuiTableCell-root.MuiTableCell-body.column-artist.MuiTableCell-sizeSmall",
  searchBarInSongs: '[id="title"]',
  songNameFromTable:
    ".MuiTableCell-root.MuiTableCell-body.column-title.MuiTableCell-sizeSmall",
  firstSongContextMenuOptions: "//tbody/tr[1]/td[11]/span[1]/button[2]",
  playNowMenuItem: '[value="playNow"]',
  fiveStarRatingSong: '[for="082f435a363c32c57d5edb6a678a28d4-5"]',
  fiveStarFilled: `[for="082f435a363c32c57d5edb6a678a28d4-5"] span[class='MuiRating-icon MuiRating-iconFilled']`,
  songNameInFavourites: ".MuiTypography-root.MuiTypography-body2",
  radiosSectionLink: "Radios",
  radiosTable:
    ".MuiPaper-root.MuiCard-root.MuiPaper-elevation1.MuiPaper-rounded",
  radioFromTable: ".MuiTableRow-root.MuiTableRow-hover",
  radioName:
    ".MuiTableCell-root.MuiTableCell-body.column-name.MuiTableCell-sizeSmall",
  homePageUrlRadio: '[rel="noopener noreferrer"]',
  sharesSectionLink: "Shares",
  shareId:
    ".MuiTableCell-root.MuiTableCell-body.column-id.MuiTableCell-sizeSmall",
  sharePagePlayButton: '[class="react-jinke-music-player-play-icon"]',
  selectShareLink: '[aria-label="Select this row"]',
  delete: '[aria-label="Delete"]',
  successMessage:
    '[class="MuiPaper-root MuiSnackbarContent-root MuiPaper-elevation6"]',
  shareFromTable: ".MuiTableRow-root.MuiTableRow-hover",
  allowDownloadsButton: '[id="downloadable"]',
  saveButton: '[aria-label="Save"]',
  downloadNotAllowedIcon: '[data-testid="false"]',
  downloadAllowedIcon: '[data-testid="true"]',
  downloadButtonInShare: '[title="Download"]',
  descriptionColumn:
    ".MuiTableCell-root.MuiTableCell-body.column-description.MuiTableCell-sizeSmall",
  shareExpireField: '[id="expiresAt"]',
  expiresColumn:
    ".MuiTableCell-root.MuiTableCell-body.column-expiresAt.MuiTableCell-sizeSmall",
  visitsColumn:
    ".MuiTableCell-root.MuiTableCell-body.column-visitCount.MuiTableCell-alignRight.MuiTableCell-sizeSmall",
  settings: ".MuiButtonBase-root.MuiIconButton-root.MuiIconButton-sizeSmall",
  createPlaylistButton: '[aria-label="Create"]',
  namePlaylistField: '[id="name"]',
  playlistCreatedAlert:
    '[class="MuiSnackbar-root MuiSnackbar-anchorOriginTopCenter"]',
  commentField: '[id="comment-label"]',
  editPlaylistButton: '[aria-label="Edit"]',
  publicButton: '[id="public"]',
  playlistTable: ".MuiTableRow-root",
  selectPlaylistButton: '[aria-label="Select this row"]',
  recentlyAddedSectionLink: "Recently Added",
  playlistSearchBar: '[id="q"]',
  playlistNameColumn:
    ".MuiTableCell-root.MuiTableCell-body.column-name.MuiTableCell-sizeSmall",
  playlistSongsColumn:
    ".MuiTableCell-root.MuiTableCell-body.column-songCount.MuiTableCell-alignRight.MuiTableCell-sizeSmall",
};
